
import joblib

_model=None
_vectorizer=None

def load_text_model():
    """
    Load the SVM model for text classification. The model is loaded from a local file along with its corresponding vectorizer. The loaded model and vectorizer are cached in global variables to avoid redundant loading on subsequent calls.

    Returns:
        tuple: A tuple containing the loaded SVM model and vectorizer.
    """
    global _model, _vectorizer
    if _model is not None and _vectorizer is not None:
        return _model, _vectorizer
    
    try:
        _model=joblib.load("assets/SVM_model.pkl")
        _vectorizer=joblib.load("assets/vectorizer.pkl")
    except Exception as e:
        print("Error loading text model:", e)
        _model=None
        _vectorizer=None
        raise

    return _model, _vectorizer

def is_loaded():
    """
    Check if the text classification model is loaded.

    Returns:
        bool: True if the model is loaded, False otherwise.
    """
    return _model is not None and _vectorizer is not None

async def predict_text(text: str):
    """
    Predict whether a given text is generated by AI or written by a human. The function takes a text string as input, processes it through the loaded vectorizer, and then passes it through the loaded SVM model to get the prediction. The output is mapped to 1 for AI-generated text and 0 for human-written text.

    Args:
        text: A string containing the text that needs to be analyzed.

    Returns:
        dict: A dictionary containing the prediction result (1 for AI-generated, 0 for human-written) and a label ("AI" or "HUMAN") based on the prediction.
    """
    model, vectorizer=load_text_model()
    if not text or len(text.strip())==0:
        return {
            "error":"Text is empty"
        }
    try:
        features=vectorizer.transform([text])
        pred=model.predict(features)[0]
        return {
            "result":int(pred),
            "label":"AI" if pred==1 else "HUMAN"
        }
    except Exception as e:
        print("Error during text prediction:", e)
        return {
            "error":"Prediction failed"
        }
    