import torch
import torch.nn as nn
from torchvision import transforms, models
import io
from PIL import Image
import numpy as np

DEVICE=torch.device("cuda" if torch.cuda.is_available() else "cpu")
_model=None

transform_pipeline=transforms.Compose([
    transforms.Resize((512,512)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

def load_image_model():
    """
    Load the EfficientNet-B0 model for image classification. The model is modified to have 2 output classes and is loaded with pre-trained weights from a local file. The model is set to evaluation mode and moved to the appropriate device (GPU if available, otherwise CPU). The loaded model is cached in a global variable to avoid redundant loading on subsequent calls.

    Returns:
        torch.nn.Module: The loaded and prepared EfficientNet-B0 model for image classification.
    """
    global _model
    if _model is not None:
        return _model
    
    m=models.efficientnet_b0(weights=None)
    m.classifier[1]=nn.Linear(m.classifier[1].in_features,2)
    m.load_state_dict(torch.load("assets/image_model.pth", map_location=DEVICE))
    m.to(DEVICE)
    m.eval()
    _model=m
    return _model

def is_loaded():
    """
    Check if the image classification model is loaded.

    Returns:
        bool: True if the model is loaded, False otherwise.
    """
    return _model is not None

def predict_frame_local(frame):
    """
    Predict whether a given video frame is generated by AI or captured from a real camera. The function takes a video frame as input, processes it through the same transformation pipeline used during training, and then passes it through the loaded EfficientNet-B0 model to get the prediction. The output is mapped to 1 for AI-generated frames and 0 for real camera frames.

    Args:
        frame: A video frame (as a NumPy array) that needs to be analyzed.

    Returns:
        int: 1 if the frame is predicted to be AI-generated, 0 if it is predicted to be from a real camera.
    """
    model=load_image_model()
    img=Image.fromarray(frame[...,::-1])
    img=transform_pipeline(img).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        output=model(img)
        pred=output.argmax(1).item()
    mapped=1 if pred==0 else 0
    return mapped

async def predict_image(file):
    """
    Predict whether a given image file is generated by AI or captured from a real camera. The function reads the image file, processes it through the same transformation pipeline used during training, and then passes it through the loaded EfficientNet-B0 model to get the prediction. The output is mapped to 1 for AI-generated images and 0 for real camera images.

    Args:
        file: An uploaded image file (e.g., from a FastAPI endpoint) that needs to be analyzed.
    
    Returns:
        dict: A dictionary containing the prediction result (1 for AI-generated, 0 for real camera) and a label ("AI" or "HUMAN") based on the prediction.
    """
    model=load_image_model()
    img_bytes=await file.read()
    img=Image.open(io.BytesIO(img_bytes)).convert("RGB")
    img=transform_pipeline(img).unsqueeze(0).to(DEVICE)

    with torch.no_grad():
        output=model(img)
        pred=output.argmax(1).item()
        mapped=1 if pred==0 else 0
        return {
            "result":mapped,
            "label":"AI" if mapped==1 else "HUMAN"
        }