//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI_vs_HUMAN.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AI_vs_HUMAN.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Potwierdzam prędkość.
        /// </summary>
        internal static string acceptSpeedButton {
            get {
                return ResourceManager.GetString("acceptSpeedButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wynik AI.
        /// </summary>
        internal static string aiScore {
            get {
                return ResourceManager.GetString("aiScore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AI pomyliło się: 0.
        /// </summary>
        internal static string aiWrong {
            get {
                return ResourceManager.GetString("aiWrong", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu WYNIK.
        /// </summary>
        internal static string answerFileCheck {
            get {
                return ResourceManager.GetString("answerFileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mini gra, pojedynek z AI.
        /// </summary>
        internal static string challangeBitton {
            get {
                return ResourceManager.GetString("challangeBitton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmień język.
        /// </summary>
        internal static string changeLang {
            get {
                return ResourceManager.GetString("changeLang", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sprawdź!!!.
        /// </summary>
        internal static string checkButton {
            get {
                return ResourceManager.GetString("checkButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Koniec, wróć.
        /// </summary>
        internal static string endButton {
            get {
                return ResourceManager.GetString("endButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu tryb nieskończony.
        /// </summary>
        internal static string endlessModeButton {
            get {
                return ResourceManager.GetString("endlessModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Szybko (co 60 klatkę).
        /// </summary>
        internal static string fastRadio {
            get {
                return ResourceManager.GetString("fastRadio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Podaj obraz do sprawdzenia.
        /// </summary>
        internal static string getPhotoButton {
            get {
                return ResourceManager.GetString("getPhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wybierz prędkość przetwarzania wideo.
        /// </summary>
        internal static string groupBoxSpeed {
            get {
                return ResourceManager.GetString("groupBoxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twój wynik.
        /// </summary>
        internal static string humanScore {
            get {
                return ResourceManager.GetString("humanScore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Co ile klatek ma być sprawdzane wideo (wartości wpisane nie mają pierwszeństwa).
        /// </summary>
        internal static string labelFast {
            get {
                return ResourceManager.GetString("labelFast", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu NIE.
        /// </summary>
        internal static string noButton {
            get {
                return ResourceManager.GetString("noButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Normalnie (co 30 klatkę).
        /// </summary>
        internal static string normalRadio {
            get {
                return ResourceManager.GetString("normalRadio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy ta grafika została wygenerowana przez AI?.
        /// </summary>
        internal static string questionMG {
            get {
                return ResourceManager.GetString("questionMG", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset.
        /// </summary>
        internal static string restartButton {
            get {
                return ResourceManager.GetString("restartButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wolno (co 15 klatkę).
        /// </summary>
        internal static string slowRadio {
            get {
                return ResourceManager.GetString("slowRadio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Uruchom model (może to zająć chwilę).
        /// </summary>
        internal static string startButton {
            get {
                return ResourceManager.GetString("startButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zacznij grę.
        /// </summary>
        internal static string startGameButton {
            get {
                return ResourceManager.GetString("startGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Super szybko (co 120 klatkę).
        /// </summary>
        internal static string superFastRadio {
            get {
                return ResourceManager.GetString("superFastRadio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Super wolno (każdą klatkę).
        /// </summary>
        internal static string superSlowRadio {
            get {
                return ResourceManager.GetString("superSlowRadio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostały czas: .
        /// </summary>
        internal static string timeLabel {
            get {
                return ResourceManager.GetString("timeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu AI miało rację:  0.
        /// </summary>
        internal static string Wy {
            get {
                return ResourceManager.GetString("Wy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu TAK.
        /// </summary>
        internal static string yesButton {
            get {
                return ResourceManager.GetString("yesButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Miałeś/-aś rację : 0.
        /// </summary>
        internal static string youRight {
            get {
                return ResourceManager.GetString("youRight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyliłeś/-łaś się : 0.
        /// </summary>
        internal static string youWrong {
            get {
                return ResourceManager.GetString("youWrong", resourceCulture);
            }
        }
    }
}
